const BOARD_WIDTH = 5;
const BOARD_LENGTH = 6;
const MAXIMUM_DEPTH = 1;
const CHECK_VALUE_IN_EVALUTION = 20;
const PLAYER_PAWN = 'p_pa';
const COMPUTER_PAWN = 'c_pa';
const [PLAYER_ROOK, COMPUTER_ROOK] = ['p_ro', 'c_ro'];
const [PLAYER_BISHOP, COMPUTER_BISHOP] = ['p_bi', 'c_bi'];
const [PLAYER_KING, COMPUTER_KING] = ['p_ki', 'c_ki'];
const [PLAYER_QUEEN, COMPUTER_QUEEN] = ['p_qu', 'c_qu'];
const [PLAYER_KNIGHT, COMPUTER_KNIGHT] = ['p_kn', 'c_kn'];




// module.exports = {
//   BOARD_WIDTH,
//   BOARD_LENGTH,

//   PLAYER_PAWN,
//   COMPUTER_PAWN,
//   PLAYER_ROOK, COMPUTER_ROOK,
//   PLAYER_BISHOP, COMPUTER_BISHOP,
//   PLAYER_KING, COMPUTER_KING,
//   PLAYER_QUEEN, COMPUTER_QUEEN,
//   PLAYER_KNIGHT, COMPUTER_KNIGHT,
//   MAXIMUM_DEPTH,
//   CHECK_VALUE_IN_EVALUTION
// };


export {
  BOARD_WIDTH,
  BOARD_LENGTH,

  PLAYER_PAWN,
  COMPUTER_PAWN,
  PLAYER_ROOK, COMPUTER_ROOK,
  PLAYER_BISHOP, COMPUTER_BISHOP,
  PLAYER_KING, COMPUTER_KING,
  PLAYER_QUEEN, COMPUTER_QUEEN,
  PLAYER_KNIGHT, COMPUTER_KNIGHT,
  MAXIMUM_DEPTH,
  CHECK_VALUE_IN_EVALUTION
};